apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    type: sidecar
spec:
  containers:
    - name: container1
      image: busybox
      command: ['sh', '-c', 'sleep 3600']

    - name: container2
      image: busybox
      command: ['sh', '-c', 'sleep 3600']