apiVersion: v1
kind: Pod
metadata:
  name: pod-5
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
      name: httpd
      protocol: TCP	
  restartPolicy: Never
