apiVersion: v1
kind: ReplicationController
metadata:
  name: website
spec:
  replicas: 3
  selector:
    type: frontend
  template:
    metadata:
      name: website
      labels:
        type: frontend
    spec:
      containers:
        - name: website
          image: tushar1907/first-app
          ports:
            - containerPort: 80
              protocol: TCP
              name: http